"""empty message

Revision ID: 214a51c2b220
Revises: 6b7beabc6f86
Create Date: 2020-09-20 21:32:16.205122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214a51c2b220'
down_revision = '6b7beabc6f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
